labels:
  # Issue Forms
  - name: bug-report
    color: "F9D0C4"
    description: 不具合報告

  - name: feature-request
    color: "C5DEF5"
    description: 新機能の提案・ご要望

  - name: help-wanted
    color: "D4C5F9"
    description: ご質問
