blank_issues_enabled: false
contact_links:
  - name: SNS-on
    url: https://sns-on.net
    about: Web Site URL
  - name: Twitter
    url: https://twitter.com/MemoryLoverz
    about: Twitter Account of Memory Lovers, LLC.
